### ISSUE TITLE
Keep getting 404 with printer/info

### ISSUE THREAD

**Issue by LeandroMarceddu** [Arksine/moonraker#10]
As the title says. Logs include only these:
21:44:55,290 [moonraker.py:_read_klippy_stream()] - Unknown command received: {"id": 3048972656, "error": {"message": "webhooks: No registered callback for path 'GET'", "error": "WebRequestError"}}

klippylog has only these:
webhooks: No registered callback for path 'GET'

What am I doing wrong?

EDIT: Forgot to mention I tried installing it both manually and by several 'scripts', most noteworthy KIAUH (https://github.com/th33xitus/kiauh). No changes; the 404 remain. 

EDIT2: Also tried Stephan's DWC2 which also seems to be unable to get info from the printer. (yes I know that's a totally different set up etc; but it might be worth mentioning)

**Comment by Arksine** [comment]
Make sure you have pulled the latest updates for both Klipper and Moonraker.   There were some significant changes to Klipper's "webhooks" functionality that required changes to Moonraker.  The master branch of both Klipper and Moonraker should now be in sync.  I will tag an official beta release soon.

Be aware that you do need to make some changes to Klipper's "default" file, as noted in the installation instructions.  It is unlikely that installers have included this since these changes were just merged yesterday.  See the [installation documentation](https://github.com/Arksine/moonraker/blob/master/docs/installation.md) for details on this.

**Comment by LeandroMarceddu** [comment]
Yup, seems you're right. I didn't know what but deleting everything and starting fresh actually did it. Thanks, my bad!
