### ISSUE TITLE
Question about cors and ports

### ISSUE THREAD

**Issue by Kragrathea** [Arksine/moonraker#215]
I am working on a web app that connects to moonraker via the api and sockets. I just had an issue with cors not working as I expected. It turns out that the port was causing the problem. I am not sure if this is the way it is supposed to work or not.

From moonraker.conf
```
cors_domains:
  *.local  #<---Won't match fluiddpi.local:7136 (my webapp) 
  *.local:*   #<---WILL match fluiddpi.local:7136 (my webapp) 
```
This sort of makes sense. But is it the way it is intended to work?

**Comment by Arksine** [comment]
Yes.  In the first entry Moonraker will accept any origin that ends with `.local`.  In the second you included a wildcard for the port, so any origin that ends with `.local` and includes a port will match.

You may have tried `.*local*` and noticed that it will produce an error, because using a wildcard to match a top level domain is unsafe.

**Comment by Kragrathea** [comment]
That makes sense. 

I was trying to avoid having to have users modify the moonraker.conf to make my app work. But I think it is going to be required. 

Unless... Could passing the api key could also allow that cors domain somehow? Probably a bad idea but I thought I would ask. :-)
