### ISSUE TITLE
Webcam isn't stable // uses a lot of CPU//crashes system

### ISSUE THREAD

**Issue by nickeeey** [Arksine/moonraker#340]
### What happened

Hi, i use a c270 webcam with Moonraker and a Raspberry Pi 3b+. The Webcam worked perfectly at octoprint, but won't work right with Moonraker. I see the picture/ Video after startup but when i switch 2-3 times to the dashboard it just loads. Also my cpu power is going up and i can't access files from the server. I tried different resoultions and framerates

### What did you expect to happen

-

### How to reproduce

C270 Webcam on Moonraker with Pi 3b+

### Additional information

-

**Comment by Arksine** [comment]
Moonraker doesn't serve the webcam stream, your issue is either with the webcam streaming daemon (mjpegstreamer, ustreamer, etc) or you are experiencing some kind of webcam driver issue.

Presumably you are using either MainsailOS or FluiddPi.  If so, I'd suggest requesting help on one of their respective discords.

**Comment by nickeeey** [comment]
Hi, Thanks and sorry. Then i Close it here
Yeah its MainSailOs
