### ISSUE TITLE
Moonraker do not update Raspberry Pi OS Packages after Recent Update

### ISSUE THREAD

**Issue by ymanyin** [Arksine/moonraker#367]
### What happened

<img width="1899" alt="Untitled" src="https://user-images.githubusercontent.com/56856272/154015599-f7743331-f393-4779-8c51-1716099fac25.png">

It was still working on v0.7.1-169-g50fd8c9.
However, update manager stopped working since recent 3-4 updates.
Thanks in advance for any help.

### Client

Fluidd

### Browser

Chrome, Firefox, Brave

### How to reproduce

Update to newest Moonraker.

**Comment by masgar** [comment]
I had the same problem after I made a apt upgrade from command line. Fixed by calling the full update API.

From POSTMAN, or any other client able to make a POST, call http://your.rpi.name/machine/update/full

After a while you will get a result: "OK" response and all your packages will be OK.

Don't know if it's a bug but I fixed in this way.

**Comment by Arksine** [comment]
Please see issue #349.  You need to grant Moonraker policykit permissions and make sure packagekit is installed.
