### ISSUE TITLE
Cant update Moonraker - Git issue

### ISSUE THREAD

**Issue by PhilBaz** [Arksine/moonraker#499]
### What happened

I cant update from Mainsail.... see image. Is this on my side?

![hgfhgf](https://user-images.githubusercontent.com/21558241/189451383-98930169-4a97-4fb3-a0cc-72c3706b156e.jpg)

### Client

Mainsail

### Browser

Chrome

### How to reproduce

press update button

**Comment by Arksine** [comment]
You have a corrupt git repo.  If Mainsail presents a recovery option you could try it (perform a "hard" recovery if available).  Otherwise can use ssh to do a [manual recovery](https://moonraker.readthedocs.io/en/latest/installation/#recovering-a-broken-repo).

Repo corruption typically occurs when power is removed from the host machine (Pi, SBC, etc) without properly shutting down.

**Comment by PhilBaz** [comment]
@Arksine 

Thank you. Manual recovery worked. I didn't see an option in MS. The recovery process also prompted me to update pip, and I did.

WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
You should consider upgrading via the '/home/pi/moonraker-env/bin/python -m pip                install --upgrade pip' command.
