### ISSUE TITLE
unable get printer info from moonraker 

### ISSUE THREAD

**Issue by marcokitt2000** [Arksine/moonraker#845]
Hello,

I have a sovol sv07 on my old klipper rpi screen hw 1.0 now allso with new version hw 1.2 i get every time i power on the system or reboot get this error.....
unable get printer info from moonraker but mainsail and fluidd works fine printer it prints only klipper screen on the screen comes retry button than it works fine it starts, or on mainsail on the upper right corner on/off button than service klipper screen restart icoon or stop than start(play buttom) it works fine. this was in begin with the usb deb update 1.0.17 or a full recovery from them 1.0.17 intermittent some times it past sometimes i must press retry. only the klipper screen for the rest works fine.
I think iget printer info from moonraker but it must wait little bit longer how can i add or more time before retry auto startup maybe it must wait what longer.

I hope in config files settings can do the trick my software on rpi klipper is OS: Armbian 22.05.0-trunk Buster maybe thats a issue.

Gr. Marco i like klipper,moonraker love it by the 1st saw and use.

**Comment by marcokitt2000** [comment]
I did a check i used from Christian Vick kpa 3.0b91 when i disabled with ; on printer.cfg file its starts normal still with the txt klipper logo unable to get printer info from moonraker but than the screen goes on. i think the time it must wait before a auto replay(maybe 1x instead off 3x times) can we adjust it where and how?

**Comment by Arksine** [comment]
Hi Marco, my understanding is that the Sovol SV7 runs a fork of Moonraker.  I would suggest contacting them for support.

At a high level, if the frontend is requesting `/printer/info` before Moonraker has had a chance to connect to Klipper then that is an issue that would need to be resolved in the frontend.  It needs to handle the error and and re-request if necessary.

**Comment by marcokitt2000** [comment]
Thank you for yours response, without Christian Vicks KPA it works fine startups fine.
https://www.printables.com/model/585691-klipper-printer-additions-30b8-more-than-boring-st
But i updated to latest versions.....
![mainsail screenshot](https://github.com/Arksine/moonraker/assets/10147001/0e9f86b6-d693-4137-8608-6780eebfb322)
check mine screenshot normal sv07 firmware release 1.0.17 or the full image is klipper v11 i use now v12.0.173 i now its now 177.
i send my klippy log and moonraker log files to.
[moonraker.log](https://github.com/Arksine/moonraker/files/15169770/moonraker.log)
[klippy.log](https://github.com/Arksine/moonraker/files/15169772/klippy.log)

Maybe someone now a trick.

Thnxxxxxx but it prints.

**Comment by marcokitt2000** [comment]
I have update to bookwurm here on github and works fine nice. thanks for evrything keep the good working klipper moonraker to work.


Gr. Marco

**Comment by Arksine** [comment]
As this appears to have been resolved I'm going to close this.

**Comment by ImhoFpV** [comment]
> I have update to bookwurm here on github and works fine nice. thanks for evrything keep the good working klipper moonraker to work.
> 
> Gr. Marco

How you update to bookwurm??

**Comment by marcokitt2000** [comment]
Yes, sovol sv07 (i think it will work fir sv07 plus is the same klipad but bjgger bed printer.cfg file).
I will post a link..... if you have sovol sv07 and has the mks v2 us emmc dongle its easy to do. On the link there is a link to img file from wo make it posible for us.


Later mail will be come...


Gr. Marco

**Comment by marcokitt2000** [comment]
https://github.com/vasyl83/SV07update


The copy trick over the 2 usb was for me not working i have copy img direct to emmc.
Than for me works fine.
If you have sovol sv07 i can upload img file there is all so kpa 3.0b91 from Christian Vick.

**Comment by ImhoFpV** [comment]
> https://github.com/vasyl83/SV07update
> 
> El truco de copiar a través de los 2 USB no me funcionó. Copié la imagen directamente a EMMC. Entonces, para mí, funciona bien. Si tienes SOVOL SV07, puedo cargar el archivo img. Todo está en KPA 3.0B91 de Christian Vick.

Hello 

Awesome friend, thanks for this
I followed the steps of the 2 usb trick, because flashing directly on the emmc didn't work for me.
It is a bit more tedious, but it seems to work.

Thanks

**Comment by ImhoFpV** [comment]
> Yes, sovol sv07 (i think it will work fir sv07 plus is the same klipad but bjgger bed printer.cfg file). I will post a link..... if you have sovol sv07 and has the mks v2 us emmc dongle its easy to do. On the link there is a link to img file from wo make it posible for us.
> 
> Later mail will be come...
> 
> Gr. Marco

Hello

Awesome friend, thanks for this
I followed the steps of the 2 usb trick, because flashing directly on the emmc didn't work for me.
It is a bit more tedious, but it seems to work.

Thanks

**Comment by ImhoFpV** [comment]
> https://github.com/vasyl83/SV07update
> 
> The copy trick over the 2 usb was for me not working i have copy img direct to emmc. Than for me works fine. If you have sovol sv07 i can upload img file there is all so kpa 3.0b91 from Christian Vick.

I have the sv07 
It would be great if you could send me the img file.

Thanks

**Comment by marcokitt2000** [comment]
please sent a email adres....

**Comment by ImhoFpV** [comment]
> please sent a email adres....

gchinea76@gmail.com

Thanks

**Comment by marcokitt2000** [comment]
https://netztorte.de/3d/doku.php?id=image
 he build a img file on it. you can download there but kpa is not in it.  i will upload my imahe with kpa in it.

**Comment by marcokitt2000** [comment]
wait i must split the file in more peaces its bigger than 2gb i can sent only 2 gbmax for free
if you have 16gb instead of 8gb emmc than this is all ready work for it. other ways you must resize it to 8gb.
the other link from totzren is withou kpa and for 8gb emmc you can download it.
its all so ok.

**Comment by ImhoFpV** [comment]
> espera, debo dividir el archivo en más partes, es más grande que 2 GB, solo puedo enviar 2 GB como máximo de forma gratuita si tienes 16 GB en lugar de 8 GB EMMC, entonces todo esto está listo para funcionar. De lo contrario, debes cambiar su tamaño a 8 GB. El otro enlace de totzren es sin kpa y para 8 GB EMMC puedes descargarlo. Todo está bien.

I have a 32gb emmc

**Comment by marcokitt2000** [comment]
i am busy uploaded to wetransfer when done i sent link

**Comment by ImhoFpV** [comment]
> i am busy uploaded to wetransfer when done i sent link

Don't worry, I'm in no hurry
I appreciate it enormously

**Comment by marcokitt2000** [comment]
10% 1 min.

**Comment by hallard** [comment]
For those who need a quick easy fix:


`KlipperScreen.service` declares `After=moonraker.service`, but **`After=` in systemd only waits for the Moonraker process to *start*** — not for Moonraker to be fully ready, and especially not for Klipper (Klippy) to finish its MCU handshake.

Moonraker proxies `/printer/*` endpoints to Klipper. Until Klippy is **ready**, those endpoints return HTTP **404**. KlipperScreen interprets that as "Unable to get info from Moonraker."

### Boot timeline observed

| Time     | Event                                                                 |
|----------|-----------------------------------------------------------------------|
| 14:40:25 | KlipperScreen starts                                                  |
| 14:40:29 | Moonraker process starts                                              |
| 14:40:34 | Moonraker ↔ Klippy socket established                                 |
| 14:40:35 | **KlipperScreen first calls `/printer/info` → 404**                   |
| 14:40:36 | KlipperScreen websocket to Moonraker connects (but `/printer/*` still 404) |
| 14:40:53 | **Klippy ready** — Moonraker can finally serve `/printer/info`        |

Gap between KlipperScreen's first request and Klippy ready: **~18 seconds**.
KlipperScreen retries every ~3s for ~5 attempts (~15s) then gives up and shows the error. Pressing **Retry** later succeeds because Klippy is by then ready.

## Fix
Make `KlipperScreen` wait until Klipper is realistically ready by adding a startup delay.
Edit `/etc/systemd/system/KlipperScreen.service`:

```ini
[Unit]
Description=KlipperScreen
After=moonraker.service
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
ExecStartPre=/bin/sleep 20
User=mks
WorkingDirectory=/home/mks/KlipperScreen
```

The only change is the added `ExecStartPre=/bin/sleep 20` line under [Service].

Reboot to verify:

`sudo reboot`

Trade-off
The splash screen stays on for ~20 extra seconds at boot, but the "Unable to get info from Moonraker" error and the manual Retry step disappear.

If 20s is not enough on your hardware (slower SD card, slower MCU handshake), bump the sleep to 25 or 30. Conversely, if Klippy reports ready faster than 20s in your journalctl -u moonraker -b | grep "Klippy ready", you can lower it.

Worked like a charm on mine, thanks Claude, took 5 minutes to fix.
